name: teleporter-compose

include:
    # Core: Contains services essential to basic operation
    - path: include.core.compose.yaml
      env_file:
        - .env
        - vpn.env

    # App: Contains basic applications providing services
    - path: include.app.compose.yaml
      env_file:
        - .env
        - vpn.env

    # Edu: Contains services that can be customised by the teaching team
    - path: include.edu.compose.yaml
      env_file:
        - .env
        - vpn.env

volumes:
  mariadb_data:
    driver: local

networks:
  oclock:
    ipam:
      driver: default
      config:
        - subnet: 10.200.0.0/16