include:
    - path: include.svc.compose.yaml
      env_file:
        - .env
        - vpn.env
    - path: include.app.compose.yaml
      env_file:
        - .env
        - vpn.env

networks:
  oclock:
    ipam:
      driver: default
      config:
        - subnet: 10.200.0.0/16
