# Teleporter App Containers

services:

  # VSCode
  vscode-server:
    container_name: teleporter-vscode
    hostname: teleporter-vscode
    image: linuxserver/code-server:4.21.2
    environment:
      PUID: 0
      PGID: 0
      TZ: ${TZ}
      LANG: ${LANG}
      DOCKER_MODS: linuxserver/mods:code-server-extension-arguments
      VSCODE_EXTENSION_IDS: ${VSCODE_EXTENSIONS_LIST}
      DEFAULT_WORKSPACE: /code
    volumes:
      - ${DATA_DIR}/configs/vscode:/config
      - ${CODE_DIR}:/code
    networks:
      oclock:
        ipv4_address: 10.200.0.14


  turn:
    container_name: teleporter-turn
    hostname: teleporter-turn
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    command: ["-v","--server-relay","-z","--min-port=49160","--max-port=49200","-r","turn.localhost","-u","zef:zef"]
    extra_hosts:
      - "turn.localhost:10.200.0.56"
    networks:
      oclock:
        ipv4_address: 10.200.0.56


  # VM service
  mavm:
    container_name: teleporter-vm
    hostname: teleporter-vm
    image: m1k1o/neko:kde
    ports:
      - "5555:5555"
      - "6666:6666/tcp"
      - "6666:6666/udp"
      - "52000-52100:52000-52100/udp"
    environment:
      #NEKO_NAT1TO1: 192.168.5.159
      #NEKO_NAT1TO1: 10.200.0.1
      #NEKO_UDPMUX: 6666
      #NEKO_TCPMUX: 6666
      NEKO_EPR: 52000-52100
      NEKO_BIND: 0.0.0.0:5555
      NEKO_ICESERVERS: '[{"urls": ["turn:turn.slippers.live:5349","stun:stun.cloudflare.com:3478" ], "username": "${TURN_USER}", "credential": "${TURN_PWD}"}]'
      #NEKO_ICESERVERS: '[{"urls": ["turn:turn.localhost", "stun:turn.localhost" ], "username": "zef", "credential": "zef"}]'
      #NEKO_ICESERVER: turn:turn.localhost:3478
      NEKO_PROXY: true
    extra_hosts:
      - "turn.localhost:10.200.0.56"
    networks:
      oclock:
        ipv4_address: 10.200.0.55
    
  # WebServer
  caddyserver:
    container_name: teleporter-caddyserver
    hostname: teleporter-caddyserver
    image: caddy:2.7.6
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    healthcheck: # https://stackoverflow.com/a/47722899/5008962
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics", "||", "exit", "1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - "${CODE_DIR}/www/public:/usr/share/caddy/"
      - "${DATA_DIR}/caddyserver/data:/data"
      - "${DATA_DIR}/caddyserver/config:/config"
      - ./containers-config/caddyserver/Caddyfile:/etc/caddy/Caddyfile
    networks:
      oclock:
        ipv4_address: 10.200.0.10

  # DBMS Access Adminer
  adminer:
    container_name: teleporter-adminer
    hostname: teleporter-adminer
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: dracula
    networks:
      oclock:
        ipv4_address: 10.200.0.12
    depends_on:
      mariaDB:
        condition: service_healthy

  # DBMS Access PHPmyAdmin
  phpmyadmin:
    container_name: teleporter-phpmyadmin
    hostname: teleporter-phpmyadmin
    image: oclock/teleporter-phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    networks:
      oclock:
        ipv4_address: 10.200.0.13
    depends_on:
      mariaDB:
        condition: service_healthy

  # DBMS Access MongoExpress
  mongo-express:
    # Be careful, the documentation on Docker Hub is outdated, use this one instead :
    # https://github.com/mongo-express/mongo-express?tab=readme-ov-file#usage-docker
    container_name: teleporter-mongo-express
    hostname: teleporter-mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_SITE_BASEURL: /mongo-express/
    networks:
      oclock:
        ipv4_address: 10.200.0.16

  # DBMS MariaDB
  mariaDB:
    container_name: teleporter-mariaDB
    hostname: teleporter-mariaDB
    image: mariadb:11.3.2
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./containers-config/mariadb/explorateur.sql:/docker-entrypoint-initdb.d/explorateur.sql
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      timeout: 30s
    networks:
      oclock:
        ipv4_address: 10.200.0.11

  # DBMS MongoDB
  mongodb:
    container_name: teleporter-mongodb
    hostname: teleporter-mongodb
    image: mongo:7.0
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      oclock:
        ipv4_address: 10.200.0.15

  # DBMS PostgreSQL
  postgreSQL:
    container_name: teleporter-postgres
    hostname: teleporter-postgres
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: js4life
    restart: always
    shm_size: 128mb
    networks:
      oclock:
        ipv4_address: 10.200.0.17

  pgadmin:
    image: dpage/pgadmin4:8.5
    depends_on:
      - postgreSQL
    hostname: teleporter-pgadmin4
    container_name: teleporter-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@oclock.io
      PGADMIN_DEFAULT_PASSWORD: js4life
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ${CONFIG_DIR}/pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      oclock:
        ipv4_address: 10.200.0.18

  # PHP
  php:
    container_name: teleporter-php
    hostname: teleporter-php
    image: php:8.3-fpm-alpine
    volumes:
      - "${CODE_DIR}/www/public:/usr/share/caddy/"
    networks:
      oclock:
        ipv4_address: 10.200.0.20
