# Teleporter App Containers

services:

  # VSCode
  vscode-server:
    container_name: teleporter-vscode
    hostname: teleporter-vscode
    image: linuxserver/code-server:4.21.2
    restart: always
    environment:
      PUID: 0
      PGID: 0
      TZ: ${TZ}
      LANG: ${LANG}
      DOCKER_MODS: linuxserver/mods:code-server-extension-arguments
      VSCODE_EXTENSION_IDS: ${VSCODE_EXTENSIONS_LIST}
      DEFAULT_WORKSPACE: /code
    volumes:
      - ${CONFIG_DIR}/vscode:/config
      - ${CODE_DIR}:/code
    networks:
      oclock:
        ipv4_address: 10.200.0.14


  turn:
    container_name: teleporter-turn
    hostname: teleporter-turn
    image: coturn/coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    command: |
      -v
      -n
      --allow-loopback-peers
      --realm=turn.localhost
      --cli-password=qergserg
      --fingerprint
      --listening-ip=0.0.0.0
      --external-ip=127.0.0.1/10.200.0.56
      --listening-port=3478
      --min-port=49160
      --max-port=49200
      --user=zef:zef
      --lt-cred-mech
      
    extra_hosts:
      - "turn.localhost:10.200.0.56"
    networks:
      oclock:
        ipv4_address: 10.200.0.56


  # VM service
  mavm:
    container_name: teleporter-vm
    hostname: teleporter-vm
    image: m1k1o/neko:xfce
    restart: always
    ports:
      - "5555:5555"
#      - "6666:6666/tcp"
#      - "6666:6666/udp"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_NAT1TO1: 192.168.5.159
      #NEKO_NAT1TO1: 10.200.0.1
      #NEKO_UDPMUX: 6666
      #NEKO_TCPMUX: 6666
      NEKO_EPR: 52000-52100
      NEKO_BIND: 0.0.0.0:5555
      NEKO_ICESERVERS: '[{"urls": ["turn:turn.slippers.live:5349","stun:stun.cloudflare.com:3478" ], "username": "${TURN_USER}", "credential": "${TURN_PWD}"}]'
      #NEKO_ICESERVERS: '[{"urls": ["turn:turn.localhost:3478", "stun:turn.localhost:3478" ], "username": "zef", "credential": "zef"}]'
      #NEKO_ICESERVER: turn:turn.localhost:3478
      #NEKO_PROXY: true
    extra_hosts:
      - "turn.localhost:10.200.0.56"
    networks:
      oclock:
        ipv4_address: 10.200.0.55
    
  # WebServer
  caddyserver:
    container_name: teleporter-caddyserver
    hostname: teleporter-caddyserver
    image: caddy:2.7.6
    restart: always
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    healthcheck: # https://stackoverflow.com/a/47722899/5008962
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics", "||", "exit", "1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - "${CODE_DIR}/www/public:/usr/share/caddy/"
      - ${CONFIG_DIR}/caddyserver/Caddyfile:/etc/caddy/Caddyfile
    networks:
      oclock:
        ipv4_address: 10.200.0.10

  # Backup
  backup:
    container_name: teleporter-backup
    hostname: teleporter-backup
    image: docker:dind
    restart: always
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - ${BACKUP_DIR}:/backup
        - ${CONFIG_DIR}/backup:/scripts
        - /var/run/docker.sock:/var/run/docker.sock
    command: /scripts/backup.sh
    networks:
      oclock:
        ipv4_address: 10.200.0.132
    depends_on:
        - mariadb
        - postgresql
        - mongodb

  # DBMS Access Adminer
  adminer:
    container_name: teleporter-adminer
    hostname: teleporter-adminer
    image: adminer:4.8.1
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: dracula
    networks:
      oclock:
        ipv4_address: 10.200.0.12
    depends_on:
      mariadb:
        condition: service_healthy

  # DBMS Access pgAdmin
  pgadmin:
    container_name: teleporter-pgadmin4
    hostname: teleporter-pgadmin4
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@oclock.io
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ${CONFIG_DIR}/pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      oclock:
        ipv4_address: 10.200.0.18
    depends_on:
      - postgresql

  # DBMS Access PHPmyAdmin
  phpmyadmin:
    container_name: teleporter-phpmyadmin
    hostname: teleporter-phpmyadmin
    image: oclock/teleporter-phpmyadmin:dd7d23c5eea0cc4d01c658a82405123cb86a2ef6
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      oclock:
        ipv4_address: 10.200.0.13
    depends_on:
      mariadb:
        condition: service_healthy

  # DBMS Access MongoExpress
  mongo-express:
    # Be careful, the documentation on Docker Hub is outdated, use this one instead :
    # https://github.com/mongo-express/mongo-express?tab=readme-ov-file#usage-docker
    container_name: teleporter-mongo-express
    hostname: teleporter-mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_SITE_BASEURL: /mongo-express/
    networks:
      oclock:
        ipv4_address: 10.200.0.16

  # DBMS MariaDB
  mariadb:
    container_name: teleporter-mariadb
    hostname: teleporter-mariadb
    image: mariadb:11.3.2
    restart: always
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ${CONFIG_DIR}/mariadb/explorateur.sql:/docker-entrypoint-initdb.d/explorateur.sql
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      timeout: 30s
    networks:
      oclock:
        ipv4_address: 10.200.0.11

  # DBMS MongoDB
  mongodb:
    container_name: teleporter-mongodb
    hostname: teleporter-mongodb
    image: mongo:7.0
    restart: always
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
    - mongodb_data:/data/db
    networks:
      oclock:
        ipv4_address: 10.200.0.15

  # DBMS PostgreSQL
  postgresql:
    container_name: teleporter-postgres
    hostname: teleporter-postgres
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    networks:
      oclock:
        ipv4_address: 10.200.0.17

  # PHP
  php:
    container_name: teleporter-php
    hostname: teleporter-php
    image: php:8.3-fpm-alpine
    restart: always
    volumes:
      - "${CODE_DIR}/www/public:/usr/share/caddy/"
    networks:
      oclock:
        ipv4_address: 10.200.0.20
