---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: "Teleporter Compose"
startUrl: http://{{HOMEPAGE_VAR_VPN_NAME}}.localhost
language: fr
disableCollapse: false
headerStyle: clean
useEqualHeights: true
hideVersion: true
statusStyle: "dot"
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
