HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<head>
    <title>Erreur 503 - Service Temporairement Indisponible</title>
    <style>
        body {
            background-color: rgba(30 41 59);
            text-align: center;
            font-family: Arial, sans-serif;
        }
        
        h1 {
            color: white;
            font-size: 36px;
            margin-top: 200px;
        }
        
        p {
            color: white;
            font-size: 24px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Erreur 503 - Service Temporairement Indisponible</h1>
    <p>Chuut, votre camarade est en train de faire une sieste.</p>
    <img src="https://lh6.googleusercontent.com/proxy/uDwmGwTA2yRsA2GwxjDwOgdWrDKKEiO2IC4hBiQK5AfxYFePDgA5X0on93rsg5JmFa3clz6m6NKAMC38pAnE3BErU-WvMfw" alt="Ronflex" width="400" height="300">
</body>
</html>