---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- O'clock:
    - Github Hati:
        - abbr: GH
          href: https://github.com/o-clock-hati/
