---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- O'clock:
    - Github {{HOMEPAGE_VAR_COHORT}}:
        - abbr: GH
          href: https://github.com/o-clock-{{HOMEPAGE_VAR_COHORT}}/
    - Slack {{HOMEPAGE_VAR_COHORT}}:
        - abbr: GH
          href: https://oclock-{{HOMEPAGE_VAR_COHORT}}.slack.com/
    - Documentation:
        - abbr: DOC
          href: https://doc.oclock.io/
- TP {{HOMEPAGE_VAR_COHORT}} :
    - Teleporter de Bras Aurélien:
        - abbr: TP
          href: http://aurelien-bras.localhost
    - Teleporter de Gineste Clément:
        - abbr: TP
          href: http://clement-gineste.localhost
    - Teleporter de Marcelino Nuno:
        - abbr: TP
          href: http://nuno-marcelino.localhost
