---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- O'clock:
    - Github {{HOMEPAGE_VAR_COHORT}}:
        - abbr: GH
          href: https://github.com/o-clock-{{HOMEPAGE_VAR_COHORT}}/