---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Utilitaires:
    - Connexion VPN:
        description: Statut de la connexion au VPN O'clock
        icon: si-openvpn
        href: https://vpn.eddi.cloud
        ping: 10.0.0.1
        statusStyle: basic
    - Accès VPN:
        description: pour générer ma configuration VPN
        icon: si-openvpn
        href: https://vpn.eddi.cloud
    - File Browser:
        href: ./file-browser
        container: teleporter-filebrowser
        description: Explorateur de fichiers dans le navigateur
        icon: mdi-folder-search-outline
    - Terminal:
        href: ./terminal
        description: Un terminal qui permet de manipuler le Téléporteur
        container: teleporter-terminal
        icon: mdi-console
    - Visual Studio Code:
        description: Editeur de code développé par Microsoft.
        icon: si-visualstudiocode
        href: ./vscode
        ping: http://localhost/vscode
- Bases de données:
    - Base de données Mysql:
        description: "Etat de la base de données MYSQL"
        icon: si-mysql
        container: teleporter-mariaDB
        statusStyle: basic
    - Base de données MongoDB:
        description: "Etat de la base de données mongoDB"
        icon: si-mongodb
        container: teleporter-mongodb
        statusStyle: basic
    - Base de données PostgresQL:
        description: "Etat de la base de données PostgresQL"
        icon: si-postgresql
        container: teleporter-postgres
        statusStyle: basic
    - Adminer:
        description: Interface graphique pour base de données PHP
        icon: si-adminer
        href: ./adminer
        ping: http://localhost/adminer
    - PhpMyAdmin:
        description: Interface graphique alternative pour base de données PHP
        icon: si-phpmyadmin
        href: ./phpmyadmin/
        ping: http://localhost/phpmyadmin/
    - Mongo Express:
        description: Interface graphique pour base de données MongoDB
        icon: mdi-database-search
        href: ./mongo-express/
        ping: http://localhost/mongo-express/
    - PgAdmin4:
        description: Interface graphique pour base de données PostgresQL
        icon: si-postgresql
        href: ./pgadmin
        ping: http://localhost/pgadmin
- Serveurs web:
    - Caddy:
        description: Sert le code situé dans le dossier /code/www/public en utilisant Caddy
        icon: si-caddy
        href: ./caddyserver
        ping: http://localhost/caddyserver
        #container: teleporter-caddyserver
    - PHP:
        description: PHP-FPM 8.3
        icon: si-php
        statusStyle: basic
        container: teleporter-php
