#!/bin/bash

# Usage if no argument
if [ -z "$1" ]; then
  echo "Usage: $0 <container_name>"
  exit 1
fi

container="$1"

# Run docker exec -it on the specified container
docker exec -it "$container" /bin/sh
