name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace image tags in include.svc.compose.yaml file
      run: |
        sed -i "s/:latest/:${{ github.sha }}/g" include.svc.compose.yaml
    
        - name: Replace image tags in include.app.compose.yaml file
        run: |
          sed -i "s/:latest/:${{ github.sha }}/g" include.app.compose.yaml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update image tags to ${{ github.sha }}"
        git push