name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Modifier selon votre branche principale

jobs:
  docker-build-tag-push:
    runs-on: ubuntu-latest
    name: Docker Build, Tag & Publish
    steps:
      - name: Build, Tag & Publish Image to DockerHub
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: containers-config/vpn/Dockerfile
          repoOwner: ${{ secrets.DOCKER_USERNAME }}
          repository:  nodejs-docker
          tag: 1.0.0

