name: Build and push vpn container

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'NunoMars-patch-1'
      
        
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: DOCKER
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            'containers-config/vpn/*'

          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./containers-config/vpn/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nunoloupy/teleporter-vpn:latest